In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.utils import np_utils

Using TensorFlow backend.


In [4]:
heart_disease = pd.read_csv('heart.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
heart_disease.target.value_counts()

1    165
0    138
Name: target, dtype: int64

In [6]:
y = heart_disease['target']

X = heart_disease.drop('target', axis=1)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=12345,
                                                    test_size=0.33)

In [9]:
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values
y_train


array([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0], dtype=int64)

In [10]:
y_train_bin = np_utils.to_categorical(y_train)[:,[0, 1]]

y_test_bin = np_utils.to_categorical(y_test)[:,[0, 1]]

In [11]:
y_train_bin

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [12]:
model = Sequential()
model.add(Dense(9, input_dim=13, activation='relu')) 
model.add(Dense(10, activation='relu' ))
model.add(Dense(2, activation='softmax')) 

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train_bin, epochs=300, batch_size=10)

Train on 203 samples
Epoch 1/300
203/203 [==============================] - 1s 6ms/sample - loss: 3.2323 - accuracy: 0.6158
Epoch 2/300
203/203 [==============================] - 0s 369us/sample - loss: 1.0774 - accuracy: 0.6256
Epoch 3/300
203/203 [==============================] - 0s 350us/sample - loss: 0.7706 - accuracy: 0.6700
Epoch 4/300
203/203 [==============================] - 0s 414us/sample - loss: 0.7470 - accuracy: 0.6502
Epoch 5/300
203/203 [==============================] - 0s 399us/sample - loss: 0.6823 - accuracy: 0.6453
Epoch 6/300
203/203 [==============================] - 0s 453us/sample - loss: 0.6543 - accuracy: 0.6749
Epoch 7/300
203/203 [==============================] - 0s 315us/sample - loss: 0.6672 - accuracy: 0.6552
Epoch 8/300
203/203 [==============================] - 0s 645us/sample - loss: 0.6345 - accuracy: 0.6552
Epoch 9/300
203/203 [==============================] - 0s 636us/sample - loss: 0.6279 - accuracy: 0.6847
Epoch 10/300
203/203 [==============

203/203 [==============================] - 0s 357us/sample - loss: 0.4669 - accuracy: 0.7586
Epoch 78/300
203/203 [==============================] - 0s 559us/sample - loss: 0.5141 - accuracy: 0.7537
Epoch 79/300
203/203 [==============================] - 0s 337us/sample - loss: 0.5025 - accuracy: 0.7438
Epoch 80/300
203/203 [==============================] - 0s 276us/sample - loss: 0.4975 - accuracy: 0.7488
Epoch 81/300
203/203 [==============================] - 0s 276us/sample - loss: 0.4613 - accuracy: 0.7833
Epoch 82/300
203/203 [==============================] - 0s 369us/sample - loss: 0.5109 - accuracy: 0.7241
Epoch 83/300
203/203 [==============================] - 0s 271us/sample - loss: 0.5144 - accuracy: 0.7537
Epoch 84/300
203/203 [==============================] - 0s 271us/sample - loss: 0.4853 - accuracy: 0.7488
Epoch 85/300
203/203 [==============================] - 0s 271us/sample - loss: 0.4524 - accuracy: 0.7931
Epoch 86/300
203/203 [==============================] - 0s 

203/203 [==============================] - 0s 290us/sample - loss: 0.3723 - accuracy: 0.8276
Epoch 154/300
203/203 [==============================] - 0s 350us/sample - loss: 0.3652 - accuracy: 0.8424
Epoch 155/300
203/203 [==============================] - 0s 276us/sample - loss: 0.3432 - accuracy: 0.8374
Epoch 156/300
203/203 [==============================] - 0s 399us/sample - loss: 0.3779 - accuracy: 0.8325
Epoch 157/300
203/203 [==============================] - 0s 315us/sample - loss: 0.3673 - accuracy: 0.8424
Epoch 158/300
203/203 [==============================] - 0s 364us/sample - loss: 0.3636 - accuracy: 0.8227
Epoch 159/300
203/203 [==============================] - 0s 507us/sample - loss: 0.3390 - accuracy: 0.8473
Epoch 160/300
203/203 [==============================] - 0s 399us/sample - loss: 0.4403 - accuracy: 0.7931
Epoch 161/300
203/203 [==============================] - 0s 325us/sample - loss: 0.3935 - accuracy: 0.8128
Epoch 162/300
203/203 [============================

203/203 [==============================] - 0s 367us/sample - loss: 0.3097 - accuracy: 0.8719
Epoch 230/300
203/203 [==============================] - 0s 359us/sample - loss: 0.3536 - accuracy: 0.8374
Epoch 231/300
203/203 [==============================] - 0s 423us/sample - loss: 0.3345 - accuracy: 0.8374
Epoch 232/300
203/203 [==============================] - 0s 261us/sample - loss: 0.3222 - accuracy: 0.8818
Epoch 233/300
203/203 [==============================] - 0s 428us/sample - loss: 0.3016 - accuracy: 0.8867
Epoch 234/300
203/203 [==============================] - 0s 482us/sample - loss: 0.3050 - accuracy: 0.8867
Epoch 235/300
203/203 [==============================] - 0s 468us/sample - loss: 0.3127 - accuracy: 0.8621
Epoch 236/300
203/203 [==============================] - 0s 423us/sample - loss: 0.3281 - accuracy: 0.8571
Epoch 237/300
203/203 [==============================] - 0s 286us/sample - loss: 0.3449 - accuracy: 0.8177
Epoch 238/300
203/203 [============================

In [13]:
scores = model.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

100/100 [==============================] - 0s 4ms/sample - loss: 0.5420 - accuracy: 0.7900

Accuracy: 79.00%


In [14]:
predictions = model.predict(X_test)

In [15]:
predictions

array([[9.72719789e-01, 2.72802357e-02],
       [1.34006768e-01, 8.65993261e-01],
       [5.91917932e-01, 4.08082098e-01],
       [8.44521344e-01, 1.55478626e-01],
       [9.67625737e-01, 3.23742554e-02],
       [9.30626765e-02, 9.06937301e-01],
       [9.89680350e-01, 1.03196660e-02],
       [2.87338167e-01, 7.12661803e-01],
       [9.35183465e-01, 6.48165420e-02],
       [1.14726303e-02, 9.88527417e-01],
       [2.06337087e-02, 9.79366243e-01],
       [7.28674559e-03, 9.92713273e-01],
       [4.04813141e-02, 9.59518611e-01],
       [3.55804265e-02, 9.64419544e-01],
       [2.97347968e-03, 9.97026503e-01],
       [6.19312525e-01, 3.80687445e-01],
       [9.90185976e-01, 9.81400535e-03],
       [9.99552667e-01, 4.47287050e-04],
       [8.54575396e-01, 1.45424530e-01],
       [1.39882296e-01, 8.60117733e-01],
       [5.12524284e-02, 9.48747575e-01],
       [3.19712944e-02, 9.68028724e-01],
       [9.99997497e-01, 2.47225466e-06],
       [1.58494115e-01, 8.41505885e-01],
       [4.946200