## Классификация вин


### Задача.  Измеряются 13 характеристик химического состава вина. Необходимо по значениям имеющихся переменных определить тип вина.

Имеются результаты химического анализа трех сортов вина, grown in the same region in Italy but derived from three different cultivars.

Сорт вина указан в трех столбцах класс_1, класс_2 и класс_3. Если в первом столбце (класс_3) стоит единица, то наблюдение соответствует виду вина третьего типа, если во втором столбце (класс_2) стоит единица, то наблюдение соответствует виду вина второго типа, если в третьем столбце (класс_1) стоит единица, то наблюдение соответствует виду вина первого типа. Таким образом, столбцы дублируют друг  друга.

Задача приобрела большую известность и активно обсуждалась. Как оказалось, статистические методы могут различать вина лучше опытного профессионального знатока вин (сомелье). Эффект после начальной публикации оказался хоть и ниже, чем от проигрыша Каспаровым (на тот момент чемпионом мира) матча шахматной программе Дип Блю» (Deep Blue) но тем не менее сопоставимым.


Список переменных:
 	1)  Alcohol (содержание алкоголя)
    
 	2)  Malic acid (яблочная кислота)
    
 	3)  Ash (зола)
    
	4)  Alcalinity of ash  
    
 	5)  Magnesium (магний)
    
	6)  Total phenols (общее содержание фенола (карболовой кислоты))
    
 	7)  Flavanoids  (ароматические вещества)
    
 	8)  Nonflavanoid phenols
    
 	9)  Proanthocyanins
    
	10) Color intensity  (интенсивность цвета)
    
 	11) Hue (окраска? красители?)
    
 	12) OD280/OD315 of diluted wines
    
 	13) Proline   (пролин)       
    

Число наблюдений – 178

Число переменных – 13, все измерены в количественной (непрерывной) шкале.

	В задаче рекомендуется (но не обязательно) провести сокращение числа переменных.

Источник задачи: UCI Machine learning Database
ftp://ftp.ics.uci.edu/pub/machine-learning-databases/wine

Обсуждение задачи:
ftp://ftp.ics.uci.edu/pub/machine-learning-databases/wine


In [ ]:
# Импорт matplotlib - не нужен, на всякий случай
# Импорт библиотек
import numpy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline

In [ ]:
# Импорт нужного из keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils


In [ ]:
# Импорт обучающей выборки
wine = pd.read_csv(r'C:\Users\Alsu1\Desktop\ИТИС_2020-21\Доп главы\нейронные сети\Wine.txt', sep='\t', header=0)


In [ ]:
wine.head()

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
0   14.23    1.71    2.43    15.6     127    2.80    3.06    0.28    2.29   
1   13.20    1.78    2.14    11.2     100    2.65    2.76    0.26    1.28   
2   13.16    2.36    2.67    18.6     101    2.80    3.24    0.30    2.81   
3   14.37    1.95    2.50    16.8     113    3.85    3.49    0.24    2.18   
4   13.24    2.59    2.87    21.0     118    2.80    2.69    0.39    1.82   

   Input10  Input11  Input12  Input13  Desired1(3)  
0     5.64     1.04     3.92     1065            0  
1     4.38     1.05     3.40     1050            0  
2     5.68     1.03     3.17     1185            0  
3     7.80     0.86     3.45     1480            0  
4     4.32     1.04     2.93      735            0

In [ ]:
wine['Desired1(3)'].value_counts(normalize=True)

2    0.398876
0    0.331461
1    0.269663
Name: Desired1(3), dtype: float64

In [ ]:
#  предикторы и отклик разделяем
# Отклик - группирующая переменная -  вектор y
y = wine['Desired1(3)']
# Предикторы - таблица X
X = wine.drop('Desired1(3)', axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=12345,
                                                    # доля объёма тестового множества
                                                    test_size=0.33)

In [ ]:
#  Преобразование pandas dataframe в numpy array
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values



In [ ]:
# Больше 2-х классов
# Классы не упорядочены
y_train_bin = np_utils.to_categorical(y_train)

y_test_bin = np_utils.to_categorical(y_test)

In [ ]:
# Почему не работает?
y_train_bin.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [ ]:
y_train_bin[0:5]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
from keras.models import Sequential # модуль снти прямого распространения
from keras.layers import Dense # модуль описания слоев


In [ ]:

# Создание модели 
model = Sequential()
model.add(Dense(9, input_dim=13, activation='relu')) # первый слой, количество нейронов=9
model.add(Dense(10, activation='relu', ))
model.add(Dense(3, activation='softmax')) # 3 выходных значения=3 класса

# достаточно много слоев и числа нейронов----> слодная нейроннная сеть
# попробовать с одним слоем и 6 нейронами

# Обучение модели, критерий качества-categorical_crossentropy, adam учитывает скорость в градиентном спуске
# минимизируем loss, проверяем accuracy
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Training a model # epochs- 300 сканирований базы, batch size - ,пропускаем 10 элементов - меняем веса
model.fit(X_train, y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
12/12 [==============================] - 0s 3ms/step - loss: 148.3610 - accuracy: 0.4118
Epoch 2/300
12/12 [==============================] - 0s 2ms/step - loss: 119.6573 - accuracy: 0.4118
Epoch 3/300
12/12 [==============================] - 0s 2ms/step - loss: 95.3787 - accuracy: 0.4118
Epoch 4/300
12/12 [==============================] - 0s 2ms/step - loss: 71.6128 - accuracy: 0.4118
Epoch 5/300
12/12 [==============================] - 0s 2ms/step - loss: 51.2493 - accuracy: 0.4118
Epoch 6/300
12/12 [==============================] - 0s 2ms/step - loss: 32.7076 - accuracy: 0.3193
Epoch 7/300
12/12 [==============================] - 0s 2ms/step - loss: 26.8489 - accuracy: 0.3193
Epoch 8/300
12/12 [==============================] - 0s 2ms/step - loss: 22.1836 - accuracy: 0.2857
Epoch 9/300
12/12 [==============================] - 0s 2ms/step - loss: 18.5271 - accuracy: 0.2017
Epoch 10/300
12/12 [==============================] - 0s 2ms/step - loss: 15.0995 - accuracy: 0.32

In [ ]:
# evaluate the model
scores = model.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

2/2 [==============================] - 0s 3ms/step - loss: 0.3901 - accuracy: 0.8644

Accuracy: 86.44%


In [ ]:
# calculate predictions
predictions = model.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [ ]:
print(predictions[0:5])

[[3.0074161e-01 0.0000000e+00 6.9925833e-01]
 [2.2982089e-01 0.0000000e+00 7.7017915e-01]
 [5.7817298e-01 0.0000000e+00 4.2182696e-01]
 [9.9435896e-01 0.0000000e+00 5.6410097e-03]
 [1.9473886e-02 1.7381439e-36 9.8052615e-01]]
